env: dev3
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  jpg:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5762
    username: guest
    password: guest
girl:
  name: lili
  age: 19
