spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://172.16.254.136:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  redis:
    host: localhost
    port: 6379
    
